  CREATE TABLE "CATEGORY" 
   (	"ID" NUMBER, 
	"CAT_NAME" VARCHAR2(50), 
	"PID" NUMBER, 
	"CREATE_BY" VARCHAR2(40), 
	"CREATE_ON" DATE, 
	"COMPANY_ID" NUMBER, 
	"ACTIVE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
