  CREATE TABLE "PO_ORDER" 
   (	"PO_NO" NUMBER, 
	"PO_ID" VARCHAR2(50), 
	"PO_DATE" DATE, 
	"PO_SUPP" VARCHAR2(50), 
	"AMOUNT" NUMBER, 
	"DISCOUNT" NUMBER, 
	"VAT" NUMBER, 
	"NET_AMOUNT" NUMBER, 
	"CREATE_BY" VARCHAR2(40), 
	"CREATE_ON" DATE, 
	"COMPANY_ID" NUMBER, 
	"CN_FLAG" NUMBER, 
	"CN_DT" DATE, 
	"CN_BY" VARCHAR2(40), 
	"CN_REASON" VARCHAR2(100), 
	"APP_FLAG" NUMBER, 
	"APP_DT" DATE, 
	"APP_BY" VARCHAR2(40), 
	 PRIMARY KEY ("PO_NO")
  USING INDEX  ENABLE
   ) ;
