  CREATE TABLE "SL_ORDER_DTL" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_NO" NUMBER, 
	"ITEM_NAME" NUMBER, 
	"RATE" NUMBER, 
	"QTY" NUMBER, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SL_ORDER_DTL" ADD CONSTRAINT "SL_ORDER_DTL_CON" FOREIGN KEY ("ORDER_NO")
	  REFERENCES "SL_ORDER" ("ORDER_NO") ENABLE;
