  CREATE TABLE "SL_ORDER" 
   (	"ORDER_NO" NUMBER, 
	"ORDER_ID" NUMBER, 
	"ORDER_DT" DATE, 
	"CUST_NAME" NUMBER, 
	"ORDER_ADDRESS" VARCHAR2(150), 
	"PAY_TYPE" NUMBER, 
	"AMOUNT" NUMBER, 
	"VAT_PR" NUMBER, 
	"VAT_AMT" NUMBER, 
	"SUB_AMT" NUMBER, 
	"DIS_PR" NUMBER, 
	"DIS_AMT" NUMBER, 
	"NET" NUMBER, 
	"CREATE_BY" NUMBER, 
	"CREATE_ON" TIMESTAMP (6), 
	"COMPANY_NO" NUMBER, 
	 PRIMARY KEY ("ORDER_NO")
  USING INDEX  ENABLE
   ) ;
