  CREATE TABLE "SUPPLIER_INFO" 
   (	"ID" NUMBER, 
	"SUPP_NAME" VARCHAR2(100), 
	"ADDRESS1" VARCHAR2(100), 
	"ADDRESS2" VARCHAR2(200), 
	"PHONE" NUMBER, 
	"PHONE2" NUMBER, 
	"EMAIL" VARCHAR2(50), 
	"ACTIVE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
