  CREATE TABLE "OTSL_USERS" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(4000), 
	"CREATED_ON" DATE, 
	"DEPARTMENT" VARCHAR2(200), 
	"AUT_SECTION" VARCHAR2(200), 
	"EXPIRES_ON" DATE, 
	"ADMIN_USER" CHAR(1), 
	"FACTORY_NAME" VARCHAR2(200), 
	"ACCESSCODE" NUMBER(20,0), 
	"ACTIVE" CHAR(2), 
	"PHONE_NO" NUMBER(12,0), 
	"PHOTO" BLOB, 
	"IMG" BLOB, 
	"MIMTYPE" VARCHAR2(50), 
	"FILENAME" VARCHAR2(100), 
	"IMAGE_LAST_UPDATE" DATE, 
	"ACCD" NUMBER
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "USER_T1" BEFORE INSERT OR UPDATE ON OTSL_USERS FOR EACH ROW
 BEGIN
:NEW.PASSWORD:=CUSTOM_HASH(UPPER(:NEW.USER_NAME),:NEW.PASSWORD);
if inserting then
IF :NEW.USER_ID IS NULL THEN 
SELECT NVL(MAX(USER_ID)+1,1) INTO :NEW.USER_ID FROM OTSL_USERS;
END if;
end if;
END;
/
ALTER TRIGGER "USER_T1" ENABLE;
